export const productsList = [
  {
    title: "bulbasaur",
    image: "https://img.pokemondb.net/artwork/bulbasaur.jpg",
    id: 1,
    price: 10,
    count: 4,
    description:
      "A strange seed was planted on its back at birth. The plant sprouts and grows with this Pokemon.",
  },
  {
    title: "ivysaur",
    image: "https://img.pokemondb.net/artwork/ivysaur.jpg",
    id: 2,
    price: 10,
    count: 4,
    description: "A Seed Pokémon that is the evolved form of Bulbasaur. It has a flower bulb on its back, the weight of which has made it develop strong legs and hips.",
  },
  {
    title: "venusaur",
    image: "https://img.pokemondb.net/artwork/venusaur.jpg",
    id: 3,
    price: 10,
    count: 4,
    description: "The plant blooms when it is absorbing solar energy. It stays on the move to seek sunlight.",
  },
  {
    title: "charmander",
    image: "https://img.pokemondb.net/artwork/charmander.jpg",
    id: 4,
    price: 10,
    count: 4,
    description: "Obviously prefers hot places. When it rains, steam is said to spout from the tip of its tail.",
  },
  {
    title: "charmeleon",
    image: "https://img.pokemondb.net/artwork/charmeleon.jpg",
    id: 5,
    price: 10,
    count: 4,
    description: "When it swings its burning tail, it elevates the temperature to unbearably high levels.",
  },
  {
    title: "charizard",
    image: "https://img.pokemondb.net/artwork/charizard.jpg",
    id: 6,
    price: 10,
    count: 4,
    description: "Spits fire that is hot enough to melt boulders. Known to cause forest fires unintentionally.",
  },
  {
    title: "squirtle",
    image: "https://img.pokemondb.net/artwork/squirtle.jpg",
    id: 7,
    price: 10,
    count: 4,
    description: "Whitaker's favorite Pokemon! After birth, its back swells and hardens into a shell. Powerfully sprays foam from its mouth.",
  },
  {
    title: "wartortle",
    image: "https://img.pokemondb.net/artwork/wartortle.jpg",
    id: 8,
    price: 10,
    count: 4,
    description: "It cleverly controls its furry ears and tail to maintain its balance while swimming.",
  },
  {
    title: "blastoise",
    image: "https://img.pokemondb.net/artwork/blastoise.jpg",
    id: 9,
    price: 10,
    count: 4,
    description: "The rocket cannons on its shell fire jets of water capable of punching holes through thick steel.",
  },
  {
    title: "caterpie",
    image: "https://img.pokemondb.net/artwork/caterpie.jpg",
    id: 10,
    price: 10,
    count: 4,
    description: "Its short feet are tipped with suction pads that enable it to tirelessly climb slopes and walls.",
  },
  {
    title: "metapod",
    image: "https://img.pokemondb.net/artwork/metapod.jpg",
    id: 11,
    price: 10,
    count: 4,
    description: "A steel-hard shell protects its tender body. It quietly endures hardships while awaiting evolution.",
  },
  {
    title: "butterfree",
    image: "https://img.pokemondb.net/artwork/butterfree.jpg",
    id: 12,
    price: 10,
    count: 4,
    description: "In battle, it flaps its wings at high speed to release highly toxic dust into the air.",
  },
  {
    title: "weedle",
    image: "https://img.pokemondb.net/artwork/weedle.jpg",
    id: 13,
    price: 10,
    count: 4,
    description: "Its poison stinger is very powerful. Its bright-colored body is intended to warn off its enemies.",
  },
  {
    title: "kakuna",
    image: "https://img.pokemondb.net/artwork/kakuna.jpg",
    id: 14,
    price: 10,
    count: 4,
    description: "While awaiting evolution, it hides from predators under leaves and in nooks of branches.",
  },
  {
    title: "beedrill",
    image: "https://img.pokemondb.net/artwork/beedrill.jpg",
    id: 15,
    price: 10,
    count: 4,
    description: "Flies at high speed and attacks using its large venomous stingers on its forelegs and tail.",
  },
  {
    title: "pidgey",
    image: "https://img.pokemondb.net/artwork/pidgey.jpg",
    id: 16,
    price: 10,
    count: 4,
    description: "Jeffrey's favorite Pokemon! Because it dislikes fighting, it protects itself by kicking up sand.",
  },
  {
    title: "pidgeotto",
    image: "https://img.pokemondb.net/artwork/pidgeotto.jpg",
    id: 17,
    price: 10,
    count: 4,
    description: "It has outstanding vision. However high it flies, it is able to distinguish the movements of its prey.",
  },
  {
    title: "pidgeot",
    image: "https://img.pokemondb.net/artwork/pidgeot.jpg",
    id: 18,
    price: 10,
    count: 4,
    description: "It spreads its gorgeous wings widely to intimidate enemies. It races through the skies at Mach-2 speed.",
  },
];
